### ISSUE TITLE
grrm2rmap error

### ISSUE THREAD

**Issue by KotaSuzu** [ReactionMap/RMapViewer#10]
To whom it may concern;
I met an error when I tried to use grrm2rmap.py.

Traceback (most recent call last):
  File "grrm2rmap.py", line 766, in <module>
    rmap = RMap(join(dirname, "grrm_"+formula))
  File "grrm2rmap.py", line 46, in __init__
    self._read_EQ_list(logfile_prefix+"_EQ_list.log")
  File "grrm2rmap.py", line 303, in _read_EQ_list
    self.EQs[eq].energy = float(line.split("=")[1].strip())
ValueError: invalid literal for float(): -0.299983234238 (  -0.299983234238 :    0.000000000000)
  

Would you teach me to fix this error?
I would be glad if you communicate with me in Japanese.
もし可能なら日本語でやり取りできるとありがたいです。

**Comment by tomooda** [comment]
The script failed to read the *_EQ_list.log file. I guess GRRM has changed the format of log files.
To make a real fix, I'd need to read the actual log files to understand the new format.
Though, I just hacked up a quick fix just to read the format in your error message.
https://raw.githubusercontent.com/tomooda/RMapViewer/issue10/scripts/grrm2rmap
Please note that this is just a quick hack and use it at your own risk.

GRRMが出力するログファイルの読み込みに失敗しているようですが、
おそらくはGRRMのファイル形式が変わったのだと思います。
正しく対応するには、ログファイル自体を読んで新しい形式を理解しなければならないのですが、
とりあえず貼り付けていただいたエラーメッセージでわかる範囲の修正をしてみました。
https://raw.githubusercontent.com/tomooda/RMapViewer/issue10/scripts/grrm2rmap
これはあくまで応急処置です。自己責任で使ってください。
正しい動作をするかは実行してみないとわかりません。

**Comment by KotaSuzu** [comment]
頂いたコードで先ほどのエラーは解消されました。しかし、
[FATAL] The babel command not found.
というエラーが発生しました。openbabelをインストールしていないのが原因だと思うのですが、どのバージョンのopenbabelをインストールすればよいのでしょうか？

**Comment by tomooda** [comment]
I recommend to use openbabel-2.x.
Please see http://openbabel.org/wiki/Install_Open_Babel_2.2

openbabel-2.xを使ってください。
ソースは http://openbabel.org/wiki/Install_Open_Babel_2.2 から入手可能です。

**Comment by KotaSuzu** [comment]
教えていただいた方法でrmapファイルの出力には成功しました。ありがとうございます。
しかし、rmapファイルを開いた際に中間体は表示されるものの遷移状態が確認できない状態になってしまいました。また、GRRMの出力ファイルには_EQ_list.logファイルと_TS_list.logは存在したものの、_DC_list.logが存在せず、代わりに_PT_list.logというファイルが存在していました。これはGRRMのバージョンの違いによるファイルの違いと考えればよいのでしょうか？また、このファイルの差異に対応するにはどうすればよいか分かりますか？

**Comment by shiroco** [comment]
Which version of GRRM do you use?

GRRMはどのバージョンをお使いですか？
